import type { Vendor } from '../types/foodhunt';

export const mockFoodVendorsChennai: Vendor[] = [
  {
    id: 'vendor_amma_kitchen',
    nameEn: "Amma's Kitchen",
    nameTa: 'அம்மாவின் சமையல்',
    areaEn: 'T. Nagar',
    areaTa: 'டி. நகர்',
    cuisines: ['South Indian', 'Filter Coffee'],
    vegType: 'veg',
    priceLevel: 1,
    rating: 4.7,
    openNow: true,
    distanceKm: 1.2,
    features: ['filter-coffee', 'home-delivery'],
    tags: ['popular', 'breakfast', 'budget'],
    lastUpdated: '2025-08-10T09:30:00+05:30',
    dishes: [
      {
        id: 'dish_idli_soft_cloud',
        nameEn: 'Soft Cloud Idli',
        nameTa: 'மேக மென்மையான இட்லி',
        price: 40,
        rating: 4.8,
        spicyLevel: 0,
        isSignature: true,
        tags: ['steamed', 'breakfast'],
        availability: 'breakfast',
        description: 'Steamed to perfection with farm-fresh coconut chutney and sambar.',
      },
      {
        id: 'dish_filter_coffee',
        nameEn: 'Degree Filter Coffee',
        nameTa: 'டிகிரி ஃபில்டர் காபி',
        price: 30,
        rating: 4.9,
        spicyLevel: 0,
        tags: ['beverage'],
        availability: 'all-day',
        description: 'Signature brass-tumbler brew with chicory aroma.',
      },
    ],
  },
  {
    id: 'vendor_dosa_house',
    nameEn: 'Mylai Dosa Kada',
    nameTa: 'மயிலை தோசை கடை',
    areaEn: 'Mylapore',
    areaTa: 'மயிலாப்பூர்',
    cuisines: ['South Indian', 'Dosa'],
    vegType: 'veg',
    priceLevel: 2,
    rating: 4.5,
    openNow: true,
    distanceKm: 2.1,
    features: ['live-dosa-counter', 'family-friendly'],
    tags: ['heritage', 'evening'],
    lastUpdated: '2025-08-08T19:10:00+05:30',
    dishes: [
      {
        id: 'dish_mysore_masala',
        nameEn: 'Mysore Masala Dosa',
        nameTa: 'மைசூர் மசாலா தோசை',
        price: 95,
        rating: 4.6,
        spicyLevel: 2,
        isSignature: true,
        tags: ['spicy', 'crispy'],
        availability: 'dinner',
        description: 'Red chutney smeared crispy dosa with potato masala.',
      },
      {
        id: 'dish_ghee_podi_dosa',
        nameEn: 'Ghee Podi Dosa',
        nameTa: 'நெய் பொடி தோசை',
        price: 110,
        rating: 4.7,
        spicyLevel: 1,
        tags: ['ghee', 'podimasala'],
        availability: 'dinner',
      },
    ],
  },
  {
    id: 'vendor_madura_mess',
    nameEn: 'Madura Mess',
    nameTa: 'மதுரா மெஸ்',
    areaEn: 'Velachery',
    areaTa: 'வேளச்சேரி',
    cuisines: ['Chettinad', 'South Indian'],
    vegType: 'mixed',
    priceLevel: 3,
    rating: 4.4,
    openNow: false,
    distanceKm: 3.8,
    features: ['chettinad-specials', 'pre-book'],
    tags: ['spicy', 'heritage'],
    lastUpdated: '2025-08-07T13:45:00+05:30',
    dishes: [
      {
        id: 'dish_kari_dosa',
        nameEn: 'Madurai Kari Dosa',
        nameTa: 'மதுரை காரி தோசை',
        price: 180,
        rating: 4.5,
        spicyLevel: 3,
        tags: ['non-veg', 'chettinad'],
        availability: 'dinner',
      },
      {
        id: 'dish_mushroom_biryani',
        nameEn: 'Mushroom Biryani',
        nameTa: 'காளான் பிரியாணி',
        price: 160,
        rating: 4.3,
        spicyLevel: 2,
        tags: ['veg', 'biryani'],
        availability: 'lunch',
      },
    ],
  },
  {
    id: 'vendor_mess_aiyaar',
    nameEn: 'Aiyappan Meals Centre',
    nameTa: 'ஐயப்பன் உணவகம்',
    areaEn: 'Triplicane',
    areaTa: 'திருவல்லிக்கேணி',
    cuisines: ['Meals', 'South Indian'],
    vegType: 'veg',
    priceLevel: 2,
    rating: 4.2,
    openNow: true,
    distanceKm: 4.5,
    features: ['banana-leaf', 'daily-special'],
    tags: ['lunch', 'traditional'],
    lastUpdated: '2025-08-09T12:30:00+05:30',
    dishes: [
      {
        id: 'dish_full_meals',
        nameEn: 'Full Lunch Meals',
        nameTa: 'முழு மதிய உணவு',
        price: 130,
        rating: 4.4,
        spicyLevel: 1,
        tags: ['banana-leaf'],
        availability: 'lunch',
      },
      {
        id: 'dish_paruppu_payasam',
        nameEn: 'Paruppu Payasam',
        nameTa: 'பருப்பு பாயசம்',
        price: 70,
        rating: 4.6,
        spicyLevel: 0,
        tags: ['dessert'],
        availability: 'lunch',
      },
    ],
  },
  {
    id: 'vendor_beach_bajji',
    nameEn: 'Marina Beach Bajji Kadai',
    nameTa: 'மெரினா பஜ்ஜி கடை',
    areaEn: 'Marina Beach',
    areaTa: 'மெரினா கடற்கரை',
    cuisines: ['Snacks', 'Street Food'],
    vegType: 'veg',
    priceLevel: 1,
    rating: 4.3,
    openNow: true,
    distanceKm: 5.6,
    features: ['sunset-spot', 'takeaway-only'],
    tags: ['street-food', 'sunset'],
    lastUpdated: '2025-08-10T18:20:00+05:30',
    dishes: [
      {
        id: 'dish_molaga_bajji',
        nameEn: 'Molaga Bajji',
        nameTa: 'மொலக பஜ்ஜி',
        price: 25,
        rating: 4.5,
        spicyLevel: 3,
        tags: ['street-food', 'spicy'],
        availability: 'all-day',
      },
      {
        id: 'dish_sundal',
        nameEn: 'Beach Sundal',
        nameTa: 'கடற்கரை சுண்டல்',
        price: 20,
        rating: 4.4,
        spicyLevel: 1,
        tags: ['street-food'],
        availability: 'all-day',
      },
    ],
  },
];
